server:
  port: 3000

spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://mysql8-container:3306/ShopApp?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Abc123456789@
  data:
    redis:
      host: redis-container
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: khanhquocphamdev@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 10000000
    expiration-refresh-token: 80000000

logging:
  level:
    root: INFO
    com.ghtk.ecommercewebsite: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

cloudinary:
  upload:
    file:
      cloud-name: dqgarzqlx
      api-key: 889522243963762
      api-secret: ${CLOUDINARY_SECRET_KEY}

stripe:
  api:
    key: ${STRIPE_API_KEY}