
version: '3.7'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456789@
      MYSQL_DATABASE: ShopApp
    ports:
      - 3307:3306
    volumes:
    - ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - shopapp-network

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - shopapp-network


  shopapp-spring-container:
    container_name: shopapp-spring-container
    build:
      context: ..
      dockerfile: Dockerfile
      #docker tag <image_id> shopapp-spring:1.0.0
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - mysql8-container
    networks:
      - shopapp-network

networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge


